#pragma once

enum e_entity_flags : int {
	fl_on_ground             = 1 << 0,
	fl_ducking               = 1 << 1,
	fl_water_jump            = 1 << 2,
	fl_on_train              = 1 << 3,
	fl_in_rain               = 1 << 4,
	fl_frozen                = 1 << 5,
	fl_at_controls           = 1 << 6,
	fl_client                = 1 << 7,
	fl_fake_client           = 1 << 8,
	fl_in_water              = 1 << 9,
	fl_fly                   = 1 << 10,
	fl_swim                  = 1 << 11,
	fl_conveyor              = 1 << 12,
	fl_npc                   = 1 << 13,
	fl_god_mode              = 1 << 14,
	fl_no_target             = 1 << 15,
	fl_aim_target            = 1 << 16,
	fl_partial_ground        = 1 << 17,
	fl_static_prop           = 1 << 18,
	fl_graphed               = 1 << 19,
	fl_grenade               = 1 << 20,
	fl_step_movement         = 1 << 21,
	fl_dont_touch            = 1 << 22,
	fl_base_velocity         = 1 << 23,
	fl_world_brush           = 1 << 24,
	fl_object                = 1 << 25,
	fl_kill_me               = 1 << 26,
	fl_on_fire               = 1 << 27,
	fl_dissolving            = 1 << 28,
	fl_trans_ragdoll         = 1 << 29,
	fl_unblockable_by_player = 1 << 30,
};